export default [
  {
    header: "Pentadbir Sistem",
    description: "Super admin",
    child: [
      {
        title: "Pengurusan Profil",
        path: "/super-admin/pengurusan-profil",
        icon: "ph:user-fill",
        child: [],
        meta: {},
      },
      {
        title: "Administrators",
        path: "/super-admin/administrators",
        icon: "ph:user-list-fill",
        child: [],
        meta: {},
      },
      {
        title: "Seller",
        path: "/super-admin/seller",
        icon: "ph:user-sound-fill",
        child: [],
        meta: {},
      },
      {
        title: "Memberships",
        path: "/super-admin/memberships",
        icon: "ph:users-fill",
        child: [],
        meta: {},
      },
      {
        title: "Global Setting Management",
        path: "/super-admin/global-setting-management",
        icon: "ph:globe-simple-bold",
        child: [],
        meta: {},
      },
      {
        title: "System Monitoring",
        path: "/super-admin/system-monitoring",
        icon: "ph:projector-screen-chart-bold",
        child: [
          {
            title: "Server Performance Metrics",
            path: "/super-admin/system-monitoring/server-performance-metrics",
            icon: "",
            child: [],
          },
          {
            title: "Application Performance Metrics",
            path: "/super-admin/system-monitoring/application-performance-metrics",
            icon: "",
            child: [],
          },
          {
            title: "Database Performance Metrics",
            path: "/super-admin/system-monitoring/database-performance-metrics",
            icon: "",
            child: [],
          },
        ],
        meta: {},
      },
      {
        title: "Integration API Keys Setting",
        path: "/super-admin/integration-api-keys-setting",
        icon: "ph:link-simple-horizontal-duotone",
        child: [],
        meta: {},
      },
    ],
    meta: {
      auth: {
        role: ["Superadmin"],
      },
    },
  },
  {
    header: "Administrator",
    description: "Admin management module",
    child: [
      {
        title: "Dashboard",
        path: "/admin/dashboard",
        icon: "ic:outline-dashboard",
        child: [],
        meta: {},
      },
      {
        title: "Profile Management",
        path: "/admin/profile-management",
        icon: "ic:round-person",
        child: [],
        meta: {},
      },
      // {
      //   title: "User Management",
      //   path: "/admin/user-management",
      //   icon: "ic:round-supervisor-account",
      //   child: [],
      //   meta: {},
      // },
      {
        title: "Product Management",
        icon: "ant-design:product-filled",
        child: [
          {
            title: "Product",
            icon: "",
            path: "/admin/product-management",
          },
          {
            title: "Category",
            icon: "",
            path: "/admin/product-management/category",
          },
          {
            title: "Product Care",
            icon: "",
            path: "/admin/product-management/product-care",
          },
        ],
        meta: {},
      },
      {
        title: "Order Management",
        path: "",
        icon: "ic:baseline-assignment",
        child: [
          {
            title: "Domestic",
            path: "/admin/order-management/domestic",
            icon: "ph:dot-outline-fill",
            meta: {},
          },
          {
            title: "Non-Domestic",
            path: "/admin/order-management/non-domestic",
            icon: "ph:dot-outline-fill",
            meta: {},
          },
          {
            title: "E-book",
            path: "/admin/order-management/e-book",
            icon: "ph:dot-outline-fill",
            meta: {},
          },
        ],
        meta: {},
      },
      // {
      //   title: "Growth Seller",
      //   path: "/admin/growth-seller",
      //   icon: "ic:outline-dashboard",
      //   child: [],
      //   meta: {},
      // },
      {
        title: "Notification Management",
        path: "/admin/notification-management",
        icon: "ic:baseline-notifications",
        child: [],
        meta: {},
      },
      {
        title: "Report Management",
        path: "/admin/report-management",
        icon: "ic:baseline-bar-chart",
        child: [
          {
            title: "User Report",
            path: "/admin/report-management/user",
            icon: "ph:dot-outline-fill",
            meta: {},
          },
          {
            title: "Product Report",
            path: "/admin/report-management/product",
            icon: "ph:dot-outline-fill",
            meta: {},
          },
        ],
        meta: {},
      },
      // {
      //   title: "Marketing Centre",
      //   path: "/admin/marketing-centre",
      //   icon: "ic:outline-dashboard",
      //   child: [],
      //   meta: {},
      // },
      {
        title: "Customer Service",
        path: "/admin/customer-service",
        icon: "ri:customer-service-2-fill",
        child: [],
        meta: {},
      },
      {
        title: "Main Page Management",
        path: "/admin/main-page-management",
        icon: "ic:sharp-view-agenda",
        child: [],
        meta: {},
      },
      // {
      //   title: "Template Management",
      //   path: "/admin/template-management",
      //   icon: "ic:sharp-file-copy",
      //   child: [],
      //   meta: {},
      // },
      {
        title: "Livestream Management",
        path: "/admin/livestream-management",
        icon: "ic:twotone-live-tv",
        child: [],
        meta: {},
      },
      {
        title: "Craft Video Management",
        path: "/admin/craft-video-management",
        icon: "ic:baseline-video-library",
        child: [],
        meta: {},
      },
      {
        title: "Craft Education Hub (webinar)",
        path: "/admin/craft-education-hub",
        icon: "ic:baseline-class",
        child: [],
        meta: {},
      },
      {
        title: "Financial Management",
        path: "/admin/financial-management",
        icon: "ic:outline-dashboard",
        child: [],
        meta: {},
      },
      // {
      //   title: "Game Management",
      //   path: "/admin/game-management",
      //   icon: "ic:outline-dashboard",
      //   child: [],
      //   meta: {},
      // },
      {
        title: "Voucher",
        path: "/admin/voucher",
        icon: "ic:baseline-local-offer",
        child: [],
        meta: {},
      },
      {
        title: "Digital Product Management",
        path: "/admin/digital-product-management",
        icon: "ant-design:product-filled",
        child: [],
        meta: {},
      },
      // {
      //   title: "Coin Management",
      //   path: "/admin/coin-management",
      //   icon: "ic:outline-dashboard",
      //   child: [],
      //   meta: {},
      // },
    ],
    meta: {
      auth: {
        role: ["Admin"],
      },
    },
  },
  {
    header: "Merchant",
    description: "Merchant business management module",
    child: [
      {
        title: "Registration",
        path: "/merchant/registration",
        icon: "material-symbols:person-add-rounded",
        child: [],
        meta: {},
      },
      {
        title: "Shop Profile",
        path: "/merchant/shop-profile",
        icon: "ph:shopping-bag-fill",
        child: [],
        meta: {},
      },
      {
        title: "Products",
        path: "",
        icon: "gridicons:product",
        child: [
          {
            title: "Add Products",
            path: "/merchant/product/add",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Manage Products",
            path: "/merchant/product/manage",
            icon: "",
            child: [],
            meta: {},
          },
        ],
        meta: {},
      },
      {
        title: "Customer Orders",
        path: "/merchant/orders",
        icon: "material-symbols-light:orders-rounded",
        child: [
          {
            title: "Manage",
            path: "/merchant/orders/manage-orders",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Return Orders",
            path: "/merchant/orders/return-orders",
            icon: "",
            child: [],
            meta: {},
          },
        ],
        meta: {},
      },
      {
        title: "Financial",
        path: "/merchant/financial",
        icon: "material-symbols:finance-mode",
        child: [
          {
            title: "Income",
            path: "/merchant/financial/income",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Balance",
            path: "/merchant/financial/balance",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Logistics Fee",
            path: "/merchant/financial/logistics-fees",
            icon: "",
            child: [],
            meta: {},
          },
        ],
        meta: {},
      },
      {
        title: "Livestream",
        path: "/merchant/livestream",
        icon: "ic:sharp-live-tv",
        child: [
          {
            title: "Livestream View",
            path: "/merchant/livestream/livestream-view",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Manage",
            path: "/merchant/livestream/manage",
            icon: "",
            child: [],
            meta: {},
          },
        ],
        meta: {},
      },
      {
        title: "Customer Service",
        path: "/merchant/customer-service",
        icon: "ri:customer-service-fill",
        child: [
          {
            title: "Manage",
            path: "/merchant/customer-service/manage",
            icon: "",
            child: [],
            meta: {},
          },
          {
            title: "Chat",
            path: "/merchant/customer-service/chat",
            icon: "",
            child: [],
            meta: {},
          },
        ],
        meta: {},
      },
      {
        title: "Notification",
        path: "/merchant/notification",
        icon: "material-symbols:notifications-rounded",
        child: [],
        meta: {},
      },
    ],
    meta: {
      auth: {
        role: ["Seller"],
      },
    },
  },
];
